services:

  bitcoind:
    image: lncm/bitcoind:v27.0
    restart: unless-stopped
    networks:
      testing_net:
        ipv4_address: 172.30.1.1
    volumes:
      - "bitcoind:/data/.bitcoin"
      - "./conf/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf"

  lnd1:
    image: lightninglabs/lnd:v0.18.0-beta.1
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.2
    command: --externalip=172.30.1.2 --externalip=lnd1:9735 --tlsextradomain=lnd1 --alias=lnd1 --color=#89CFF0
    volumes:
      - "lnd1:/root/.lnd"
      - "./conf/lnd/lnd.conf:/root/.lnd/lnd.conf"

  lndk1:
    build: ./docker/lndk
    restart: unless-stopped
    depends_on:
      - lnd1
    command: --address=https://lnd1:10009 --cert-path=/root/.lnd/tls.cert --macaroon-path=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon --log-level=trace --grpc-host=0.0.0.0
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "lnd1:/root/.lnd"
      - "lndk1:/root/.lndk"
    networks:
      testing_net:
        ipv4_address: 172.30.1.3

  cln1:
    image: elementsproject/lightningd:v24.05
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.30
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.1.30:9735 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln1 --rgb=FF0000
    volumes:
      - "cln1:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin"
      - "./conf/cln/config:/root/.lightning/config"

  eclair1:
    build: ./docker/eclair
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/data/logback-custom.xml
    volumes:
      - "eclair1:/data"
      - "./conf/eclair/eclair1.conf:/data/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/data/logback-custom.xml"

  lnd2:
    image: lightninglabs/lnd:v0.18.0-beta.1
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.1
    command: --externalip=172.30.2.1 --externalip=lnd2:9735 --tlsextradomain=lnd2 --alias=lnd2 --color=#89CFF0
    volumes:
      - "lnd2:/root/.lnd"
      - "./conf/lnd/lnd.conf:/root/.lnd/lnd.conf"

  lndk2:
    build: ./docker/lndk
    restart: unless-stopped
    depends_on:
      - lnd2
    command: --address=https://lnd2:10009 --cert-path=/root/.lnd/tls.cert --macaroon-path=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon --log-level=trace --grpc-host=0.0.0.0
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "lnd2:/root/.lnd"
      - "lndk2:/root/.lndk"
    networks:
      testing_net:
        ipv4_address: 172.30.2.2

  cln2:
    image: elementsproject/lightningd:v24.05
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.30
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.2.30:9735 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln2 --rgb=FF0000
    volumes:
      - "cln2:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin"
      - "./conf/cln/config:/root/.lightning/config"

  eclair2:
    build: ./docker/eclair
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/data/logback-custom.xml
    volumes:
      - "eclair2:/data"
      - "./conf/eclair/eclair2.conf:/data/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/data/logback-custom.xml"

  cln3:
    image: elementsproject/lightningd:v24.05
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.3.30
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.3.30:9735 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln3 --rgb=FF0000
    volumes:
      - "cln3:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin"
      - "./conf/cln/config:/root/.lightning/config"

  eclair3:
    build: ./docker/eclair
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.3.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/data/logback-custom.xml
    volumes:
      - "eclair3:/data"
      - "./conf/eclair/eclair3.conf:/data/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/data/logback-custom.xml"

  blockgen:
    build: ./docker/blockgen
    command: [ "/bin/sh", "/app/blockgen.sh" ]
    networks:
      testing_net:
        ipv4_address: 172.30.9.1
    volumes:
      - "./docker/blockgen/blockgen.sh:/app/blockgen.sh"
    depends_on:
      - bitcoind

  lnvisapi:
      image: maxkotlan/ln-visualizer-api:v0.0.28
      restart: on-failure
      networks:
        testing_net:
          ipv4_address: 172.30.10.0
      volumes:
          - "lnd1:/lnd:ro"
      environment:
          LND_CERT_FILE: '/lnd/tls.cert'
          LND_MACAROON_FILE: '/lnd/data/chain/bitcoin/regtest/readonly.macaroon'
          LND_SOCKET: lnd1:10009

  lnvisweb:
      image: maxkotlan/ln-visualizer-web:v0.0.28
      restart: on-failure
      networks:
        testing_net:
          ipv4_address: 172.30.10.1
      ports:
          - '5646:80'
      environment:
          LN_VISUALIZER_API_URL: 'http://lnvisapi:5647'

volumes:
  bitcoind:
  lnd1:
  lndk1:
  cln1:
  eclair1:
  lnd2:
  lndk2:
  cln2:
  eclair2:
  cln3:
  eclair3:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16