services:
  lnd1:
    image: lightninglabs/lnd:v0.18.0-beta.1
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.2
    command: --externalip=172.30.1.2 --externalip=lnd1:9735 --tlsextradomain=lnd1 --alias=lnd1 --color=#89CFF0
    volumes:
      - "lnd1:/root/.lnd"
      - "./conf/lnd/lnd.conf:/root/.lnd/lnd.conf"

  lndk1:
    build: ./docker/lndk
    restart: unless-stopped
    depends_on:
      - lnd1
    entrypoint: ["/wait-for-lnd.sh", "lnd1", "5"]
    command: --address=https://lnd1:10009 --cert-path=/root/.lnd/tls.cert --macaroon-path=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon --log-level=trace --grpc-host=0.0.0.0
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "lndk1:/root/.lndk"
      - "lnd1:/root/.lnd:ro"
      - "./docker/lndk/wait-for-lnd.sh:/wait-for-lnd.sh"
    networks:
      testing_net:
        ipv4_address: 172.30.1.3

  cln1:
    build: ./docker/cln
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.30
    entrypoint: ["/wait-for-bitcoind.sh"]
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.1.30:9735 --bitcoin-retry-timeout=180 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln1 --rgb=FF0000
    volumes:
      - "cln1:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin:ro"
      - "./conf/cln/config:/root/.lightning/config"
      - "./docker/cln/wait-for-bitcoind.sh:/wait-for-bitcoind.sh"

  eclair1:
    image: lnzap/eclair:0.10.0.strike.2
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.1.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/eclair/logback-custom.xml
    volumes:
      - "eclair1:/data"
      - "./conf/eclair/eclair1.conf:/eclair/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/eclair/logback-custom.xml"

  ldknode1:
    build: ./docker/ldknode
    restart: unless-stopped
    depends_on:
      - electrs
    networks:
      testing_net:
        ipv4_address: 172.30.1.32
    command: /root/.ldknode 172.30.1.32:9735 regtest http://electrs:3002
    volumes:
      - "ldknode1:/root/.ldknode"

  lnd2:
    image: lightninglabs/lnd:v0.18.0-beta.1
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.1
    command: --externalip=172.30.2.1 --externalip=lnd2:9735 --tlsextradomain=lnd2 --alias=lnd2 --color=#89CFF0
    volumes:
      - "lnd2:/root/.lnd"
      - "./conf/lnd/lnd.conf:/root/.lnd/lnd.conf"

  lndk2:
    build: ./docker/lndk
    restart: unless-stopped
    depends_on:
      - lnd2
    entrypoint: ["/wait-for-lnd.sh", "lnd2", "5"]
    command: --address=https://lnd2:10009 --cert-path=/root/.lnd/tls.cert --macaroon-path=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon --log-level=trace --grpc-host=0.0.0.0
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "lndk2:/root/.lndk"
      - "lnd2:/root/.lnd:ro"
      - "./docker/lndk/wait-for-lnd.sh:/wait-for-lnd.sh"
    networks:
      testing_net:
        ipv4_address: 172.30.2.2

  cln2:
    build: ./docker/cln
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.30
    entrypoint: ["/wait-for-bitcoind.sh"]
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.2.30:9735 --bitcoin-retry-timeout=180 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln2 --rgb=FF0000
    volumes:
      - "cln2:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin:ro"
      - "./conf/cln/config:/root/.lightning/config"
      - "./docker/cln/wait-for-bitcoind.sh:/wait-for-bitcoind.sh"

  eclair2:
    image: lnzap/eclair:0.10.0.strike.2
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.2.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/eclair/logback-custom.xml
    volumes:
      - "eclair2:/data"
      - "./conf/eclair/eclair2.conf:/eclair/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/eclair/logback-custom.xml"

  ldknode2:
    build: ./docker/ldknode
    restart: unless-stopped
    depends_on:
      - electrs
    networks:
      testing_net:
        ipv4_address: 172.30.2.32
    command: /root/.ldknode 172.30.2.32:9735 regtest http://electrs:3002
    volumes:
      - "ldknode2:/root/.ldknode"

  cln3:
    build: ./docker/cln
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.3.30
    entrypoint: ["/wait-for-bitcoind.sh"]
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.3.30:9735 --bitcoin-retry-timeout=180 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln3 --rgb=FF0000
    volumes:
      - "cln3:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin:ro"
      - "./conf/cln/config:/root/.lightning/config"
      - "./docker/cln/wait-for-bitcoind.sh:/wait-for-bitcoind.sh"

  eclair3:
    image: lnzap/eclair:0.10.0.strike.2
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      testing_net:
        ipv4_address: 172.30.3.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/eclair/logback-custom.xml
    volumes:
      - "eclair3:/data"
      - "./conf/eclair/eclair3.conf:/eclair/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/eclair/logback-custom.xml"

# --- Additional services ---

  bitcoind:
    image: lncm/bitcoind:v27.0
    restart: unless-stopped
    networks:
      testing_net:
        ipv4_address: 172.30.1.1
    volumes:
      - "bitcoind:/data/.bitcoin"
      - "./conf/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf"

  electrs:
    image: blockstream/esplora:electrs-cd9f90c115751eb9d2bca9a4da89d10d048ae931
    platform: linux/amd64
    depends_on:
      - bitcoind
    command: >
      "/app/electrs_bitcoin/bin/electrs"
      "-vvvv"
      "--timestamp"
      "--jsonrpc-import"
      "--cookie=user:pass"
      "--network=regtest"
      "--daemon-rpc-addr=bitcoind:43782"
      "--http-addr=0.0.0.0:3002"
    ports:
      - "3002:3002"
    networks:
      - testing_net

  blockgen:
    build: ./docker/blockgen
    command: [ "/bin/sh", "/app/blockgen.sh" ]
    networks:
      testing_net:
        ipv4_address: 172.30.9.1
    volumes:
      - "./docker/blockgen/blockgen.sh:/app/blockgen.sh"
    depends_on:
      - bitcoind

  lnvisapi:
      image: maxkotlan/ln-visualizer-api:v0.0.28
      restart: on-failure
      networks:
        testing_net:
          ipv4_address: 172.30.10.0
      volumes:
          - "lnd1:/lnd:ro"
      environment:
          LND_CERT_FILE: '/lnd/tls.cert'
          LND_MACAROON_FILE: '/lnd/data/chain/bitcoin/regtest/readonly.macaroon'
          LND_SOCKET: lnd1:10009

  lnvisweb:
      image: maxkotlan/ln-visualizer-web:v0.0.28
      restart: on-failure
      networks:
        testing_net:
          ipv4_address: 172.30.10.1
      ports:
          - '5646:80'
      environment:
          LN_VISUALIZER_API_URL: 'http://lnvisapi:5647'

volumes:
  bitcoind:
  lnd1:
  lndk1:
  cln1:
  eclair1:
  ldknode1:
  lnd2:
  lndk2:
  cln2:
  eclair2:
  ldknode2:
  cln3:
  eclair3:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
