name: Smoke Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Wait for services to start
      uses: hoverkraft-tech/compose-action@v0.0.0
      with:
        up-flags: "-d"

    - name: Run init script
      run: ./scripts/init.sh
